$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1465812639666.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b0d53d0ccd9d4ed99e3c9b5cda6d77eb",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2ebefca2497b47ec86d84bf889b570a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-20,
              "y":-27},
            "size":{
              "width":3170,
              "height":1457}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85a1766bd4c9413f9d4b62ac0c41d0dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-20,
                  "y":-27},
                "size":{
                  "width":3170,
                  "height":1457}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"db85303b6d9a4c9e98938e59abb6d280",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1964,
              "y":383},
            "size":{
              "width":36,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e345cc07634541ba78f16e4e378d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1964,
                  "y":383},
                "size":{
                  "width":36,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 文档查询 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["a7714999b1a44a949cb3c93b37e8e74e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"61afe791cf9e464bb1663456d36ac63c",
          "label":"模板节点设置",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1070,
              "y":358},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a15dcc088e8a4b90899a4de4a5db42f1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2c5d3bdda6ab409187177853a038c18a",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1440,
                      "height":990}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"397ef46870a24d059ffc70c5c3a8ac39",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1440,
                          "height":990}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"96c692bc1864478081f376ee5cda955d",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":51,
                      "y":494},
                    "size":{
                      "width":97,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05d47a57bb3b40b4a8d37bb5fc7fa645",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":51,
                          "y":494},
                        "size":{
                          "width":97,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a12e754fbd543f5804cba5e560cac61",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":39,
                      "y":154},
                    "size":{
                      "width":121,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1a4868164ce453988d2bad7b3091c6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":39,
                          "y":154},
                        "size":{
                          "width":121,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"36d9070d71354798b34c0bb597af702a",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":51,
                      "y":724},
                    "size":{
                      "width":97,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3b9eb2b8fc744009b2f1b9baed60946",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":51,
                          "y":724},
                        "size":{
                          "width":97,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"31f7adf9be0642639b6c440afe39f49a",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":168,
                      "y":494},
                    "size":{
                      "width":108,
                      "height":28},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ccecaf764afc44debab603e4a3a2166c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":168,
                          "y":494},
                        "size":{
                          "width":108,
                          "height":28},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u13.png"}},
{
                  "id":"ab9d8ba5953540d7b122015f1d586911",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":168,
                      "y":724},
                    "size":{
                      "width":108,
                      "height":28},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"845e9d0b68354036a9b24406b86cbc87",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":168,
                          "y":724},
                        "size":{
                          "width":108,
                          "height":28},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u13.png"}},
{
                  "id":"93f76c7a86e445c587734d32077b7227",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":540},
                    "size":{
                      "width":1176,
                      "height":161}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4821d4c1ea574c9587abd89d079bfe78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":540},
                        "size":{
                          "width":1176,
                          "height":161}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u17.png"}},
{
                  "id":"844d23eb99224cb8a67cf2dc10f34952",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":540},
                    "size":{
                      "width":1176,
                      "height":51}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7714178c94084c749e23f05df1823300",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":540},
                        "size":{
                          "width":1176,
                          "height":51}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u19.png"}},
{
                  "id":"e9cc0bc8bffb4be9b5b1582aea72a638",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":542},
                    "size":{
                      "width":261,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "placeholderText":"输入初始文件名称"},
{
                  "id":"5b1acf9e5e0240898fc02ab8eca90822",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":175,
                      "y":661},
                    "size":{
                      "width":82,
                      "height":34},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b9d12dfffa5470f94c260e5a11658f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":175,
                          "y":661},
                        "size":{
                          "width":82,
                          "height":34},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u22.png"}},
{
                  "id":"b6bfc577227b4f269ff5e38f4170179e",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":263,
                      "y":661},
                    "size":{
                      "width":82,
                      "height":34},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d84bb4d9555146409573dba2412329a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":263,
                          "y":661},
                        "size":{
                          "width":82,
                          "height":34},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u22.png"}},
{
                  "id":"309e3c41e8494f7baf47caab069f5c37",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":1304,
                      "y":548},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"60"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80607ccb46cb4e449a1904c2aad01617",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":1304,
                          "y":548},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"60"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u26.png"}},
{
                  "id":"fe4ce9eb820646ff95524407255bd206",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":771},
                    "size":{
                      "width":562,
                      "height":51}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8ac9962911f4e87a4cb61c2f62af3e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":771},
                        "size":{
                          "width":562,
                          "height":51}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u28.png"}},
{
                  "id":"4bcbd12207fb4641a816385a0adbbac2",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":773},
                    "size":{
                      "width":261,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "placeholderText":"输入结果文件名称"},
{
                  "id":"27afb0e6a9df4b998593a8b3376bfbce",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":680,
                      "y":780},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"60"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fe2fd0ec74848958636023a498e53c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":680,
                          "y":780},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"60"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u26.png"}},
{
                  "id":"7adc74b8fe274f938fdd4d474a93fec1",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":154},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"3cb59ff7a9724bca948dc89222337a16",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":154},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"b463b57f1def46239e64ce87da2f5d77",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":202},
                    "size":{
                      "width":1188,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07c42bc1cd6d49a799d7a0311d535e5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":202},
                        "size":{
                          "width":1188,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u35.png"}},
{
                  "id":"8ada306617a542bea26d86afb7d5afbd",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":1236,
                      "y":132},
                    "size":{
                      "width":120,
                      "height":50},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc7e425a78b345bfa299e2d43b541953",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":1236,
                          "y":132},
                        "size":{
                          "width":120,
                          "height":50},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u37.png"}},
{
                  "id":"01444ac81bfb434b9dddf8c1200b1aaf",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":332},
                    "size":{
                      "width":1188,
                      "height":139}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d16c5977e66741f1b7ce3571a61cefb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":332},
                        "size":{
                          "width":1188,
                          "height":139}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u39.png"}},
{
                  "id":"49f13855288743ef8a3a5b6a619c0528",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":180,
                      "y":282},
                    "size":{
                      "width":82,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"feda06ea4b44419d952e410b78f2a35a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":180,
                          "y":282},
                        "size":{
                          "width":82,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 文件 淡入淡出 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["bf4a876a27dd4fb69a13ce1b1bd32b94"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u41.png"}},
{
                  "id":"cf178665c6384e62b01ecbdc74717689",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":180,
                      "y":432},
                    "size":{
                      "width":82,
                      "height":26},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d91de061ae2480f978cd8a097de88e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":180,
                          "y":432},
                        "size":{
                          "width":82,
                          "height":26},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u43.png"}},
{
                  "id":"414988f92ea24303a89d921154df8a2b",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "location":{
                      "x":214,
                      "y":602},
                    "size":{
                      "width":101,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54cbb48a131c45718c6c8741234b5e3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "location":{
                          "x":214,
                          "y":602},
                        "size":{
                          "width":101,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fd5e790fc837482587c7120e88488be2",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":189,
                      "y":216},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5de6154cf59246e28bb632a32b94a066",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":189,
                          "y":216},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"7dc361acaa1845babbe55850042291bf",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":177,
                      "y":598},
                    "size":{
                      "width":27,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2fd8b5f40164e85a6e69e25eb5bdb06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":177,
                          "y":598},
                        "size":{
                          "width":27,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.png"}},
{
                  "id":"07dc4dc33bad4980b2331c8d360c86cb",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "location":{
                      "x":256,
                      "y":212},
                    "size":{
                      "width":47,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"682ebee2de9e4c04b1ec01db94fb78d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "location":{
                          "x":256,
                          "y":212},
                        "size":{
                          "width":47,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dca9e21cf16042cc89e2ee10ab7fd66e",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":219,
                      "y":208},
                    "size":{
                      "width":27,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"754be820a12e4058af6036a5c34d4667",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":219,
                          "y":208},
                        "size":{
                          "width":27,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.png"}},
{
                  "id":"468e590a5cb048c29f3d4f6034e934e9",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":342,
                      "y":216},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fb28c6e68c6404589b1ef291510846f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":342,
                          "y":216},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ececf9a51ff44cb8a2101647a3a63be2",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "location":{
                      "x":409,
                      "y":212},
                    "size":{
                      "width":47,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f87bf6286c14aa4b5063a35e207ad5c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "location":{
                          "x":409,
                          "y":212},
                        "size":{
                          "width":47,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"77c1c8c8ef1647feb38cc3709628913c",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":372,
                      "y":208},
                    "size":{
                      "width":27,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1968f181734e45149e3d508b44b90128",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":372,
                          "y":208},
                        "size":{
                          "width":27,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.png"}},
{
                  "id":"ace2591e44dc495f8625403d3857e0aa",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":486,
                      "y":216},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"70a5dc45b76e46cabe1850363bb23071",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":486,
                          "y":216},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"20cc7ebafd2241b08b3f28934cb8a7b3",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "location":{
                      "x":553,
                      "y":212},
                    "size":{
                      "width":47,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64c1d908f95845fc9461b36596d2cd12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "location":{
                          "x":553,
                          "y":212},
                        "size":{
                          "width":47,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0042b545efa449f5b0b9b553d9c93467",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":516,
                      "y":208},
                    "size":{
                      "width":27,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"038c6f8d71e9452aa3825be1f5bc961f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":516,
                          "y":208},
                        "size":{
                          "width":27,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.png"}},
{
                  "id":"e97cc1f4e5d14c5bac24a0c083ac7d42",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":626,
                      "y":154},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"770594510d044d58a6abc63f8c32e42f",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":42.5,
                      "y":65},
                    "size":{
                      "width":97,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d38e80368d6c4eb6afcde1722c3a0ef3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":42.5,
                          "y":65},
                        "size":{
                          "width":97,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9006cd27347642afbdd173a5f90ba967",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":161.5,
                      "y":60},
                    "size":{
                      "width":261,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "placeholderText":"输入节点名称"},
{
                  "id":"bf4a876a27dd4fb69a13ce1b1bd32b94",
                  "label":"文件",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":189,
                      "y":352},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"6335a02a5bb4479290b0b583e92cf335",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"862cbc57768b4f39bda6e8258143308e",
                          "label":"",
                          "parentDynamicPanel":"bf4a876a27dd4fb69a13ce1b1bd32b94",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Normal', 'Arial'",
                            "fontSize":"18px",
                            "fontWeight":"400",
                            "location":{
                              "x":37,
                              "y":4},
                            "size":{
                              "width":47,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fffc0bced9f54b619d0d8ed2dc6a6c2f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"bf4a876a27dd4fb69a13ce1b1bd32b94",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Normal', 'Arial'",
                                "fontSize":"18px",
                                "fontWeight":"400",
                                "location":{
                                  "x":37,
                                  "y":4},
                                "size":{
                                  "width":47,
                                  "height":25}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"8af4042ea202431683168338a98e7b09",
                          "label":"",
                          "parentDynamicPanel":"bf4a876a27dd4fb69a13ce1b1bd32b94",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":27,
                              "height":31}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f7e5c5cb6d664e8a81388ed761e99a69",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"bf4a876a27dd4fb69a13ce1b1bd32b94",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":27,
                                  "height":31}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u49.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"8a714fa1c4ac4d2bb840dfd830fd9362",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "location":{
                      "x":460,
                      "y":784},
                    "size":{
                      "width":127,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06840034ed384d74b9f52cf9189de97a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"400",
                        "location":{
                          "x":460,
                          "y":784},
                        "size":{
                          "width":127,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5f3e2fdb6c2b456d9a593e30cf312163",
                  "label":"",
                  "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF66CCCC},
                    "location":{
                      "x":156,
                      "y":882},
                    "size":{
                      "width":574,
                      "height":50},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"864a3bdfd8244b0ab812ed81c2206690",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"61afe791cf9e464bb1663456d36ac63c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CCCC},
                        "location":{
                          "x":156,
                          "y":882},
                        "size":{
                          "width":574,
                          "height":50},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 模板节点设置 淡入淡出 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["61afe791cf9e464bb1663456d36ac63c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ad5529c09540421f9420c1a6266ce5a5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1745,
              "y":397},
            "size":{
              "width":205,
              "height":113}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 模板节点设置 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["61afe791cf9e464bb1663456d36ac63c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a7714999b1a44a949cb3c93b37e8e74e",
          "label":"文档查询",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1950,
              "y":321.5},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 文档查询 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["a7714999b1a44a949cb3c93b37e8e74e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3af6af8303184e9ab15a90e3c9cbf627",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"58df245d720a49638865fc9b874a4bcf",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":220,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fb69b7e2a624a52862e96951ae6b54d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":220,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u82.png"}},
{
                  "id":"d2fdb26380b240e1a8b2f52bc033cc19",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "location":{
                      "x":44,
                      "y":32},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01d97f4ab3eb451797974d36ef103a18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "location":{
                          "x":44,
                          "y":32},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f03548610f734ef3b488a09e92a0197b",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "location":{
                      "x":44,
                      "y":71},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05a69e6008a54b89aba86d1a0bedc0f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "location":{
                          "x":44,
                          "y":71},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71664971beda42bbb85e52f008b89e66",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "location":{
                      "x":44,
                      "y":110},
                    "size":{
                      "width":71,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5aeaff1a2f7744c29ca60bd3339f43d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "location":{
                          "x":44,
                          "y":110},
                        "size":{
                          "width":71,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"443fbcd152694ed5bdcba7c39b9fd241",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":129,
                      "y":20},
                    "size":{
                      "width":19,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fca1c1a11cd5454ab919d5e811c3312b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":129,
                          "y":20},
                        "size":{
                          "width":19,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"617b66764f194099b16f4bc8a6f17063",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":59},
                    "size":{
                      "width":19,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4104d27500054eb0bb51e0beda042fc5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":59},
                        "size":{
                          "width":19,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"82bccdde15d94156b2ae0b19ef2d0dd0",
                  "label":"",
                  "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":127,
                      "y":101},
                    "size":{
                      "width":37,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25829e76fc1f47a7a3f5d9fdeb7b4d37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a7714999b1a44a949cb3c93b37e8e74e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":127,
                          "y":101},
                        "size":{
                          "width":37,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "2ebefca2497b47ec86d84bf889b570a9":{
      "scriptId":"u0"},
    "85a1766bd4c9413f9d4b62ac0c41d0dc":{
      "scriptId":"u1"},
    "db85303b6d9a4c9e98938e59abb6d280":{
      "scriptId":"u2"},
    "82e345cc07634541ba78f16e4e378d5d":{
      "scriptId":"u3"},
    "61afe791cf9e464bb1663456d36ac63c":{
      "scriptId":"u4"},
    "2c5d3bdda6ab409187177853a038c18a":{
      "scriptId":"u5"},
    "397ef46870a24d059ffc70c5c3a8ac39":{
      "scriptId":"u6"},
    "96c692bc1864478081f376ee5cda955d":{
      "scriptId":"u7"},
    "05d47a57bb3b40b4a8d37bb5fc7fa645":{
      "scriptId":"u8"},
    "8a12e754fbd543f5804cba5e560cac61":{
      "scriptId":"u9"},
    "d1a4868164ce453988d2bad7b3091c6a":{
      "scriptId":"u10"},
    "36d9070d71354798b34c0bb597af702a":{
      "scriptId":"u11"},
    "f3b9eb2b8fc744009b2f1b9baed60946":{
      "scriptId":"u12"},
    "31f7adf9be0642639b6c440afe39f49a":{
      "scriptId":"u13"},
    "ccecaf764afc44debab603e4a3a2166c":{
      "scriptId":"u14"},
    "ab9d8ba5953540d7b122015f1d586911":{
      "scriptId":"u15"},
    "845e9d0b68354036a9b24406b86cbc87":{
      "scriptId":"u16"},
    "93f76c7a86e445c587734d32077b7227":{
      "scriptId":"u17"},
    "4821d4c1ea574c9587abd89d079bfe78":{
      "scriptId":"u18"},
    "844d23eb99224cb8a67cf2dc10f34952":{
      "scriptId":"u19"},
    "7714178c94084c749e23f05df1823300":{
      "scriptId":"u20"},
    "e9cc0bc8bffb4be9b5b1582aea72a638":{
      "scriptId":"u21"},
    "5b1acf9e5e0240898fc02ab8eca90822":{
      "scriptId":"u22"},
    "4b9d12dfffa5470f94c260e5a11658f6":{
      "scriptId":"u23"},
    "b6bfc577227b4f269ff5e38f4170179e":{
      "scriptId":"u24"},
    "d84bb4d9555146409573dba2412329a2":{
      "scriptId":"u25"},
    "309e3c41e8494f7baf47caab069f5c37":{
      "scriptId":"u26"},
    "80607ccb46cb4e449a1904c2aad01617":{
      "scriptId":"u27"},
    "fe4ce9eb820646ff95524407255bd206":{
      "scriptId":"u28"},
    "e8ac9962911f4e87a4cb61c2f62af3e3":{
      "scriptId":"u29"},
    "4bcbd12207fb4641a816385a0adbbac2":{
      "scriptId":"u30"},
    "27afb0e6a9df4b998593a8b3376bfbce":{
      "scriptId":"u31"},
    "9fe2fd0ec74848958636023a498e53c8":{
      "scriptId":"u32"},
    "7adc74b8fe274f938fdd4d474a93fec1":{
      "scriptId":"u33"},
    "3cb59ff7a9724bca948dc89222337a16":{
      "scriptId":"u34"},
    "b463b57f1def46239e64ce87da2f5d77":{
      "scriptId":"u35"},
    "07c42bc1cd6d49a799d7a0311d535e5a":{
      "scriptId":"u36"},
    "8ada306617a542bea26d86afb7d5afbd":{
      "scriptId":"u37"},
    "bc7e425a78b345bfa299e2d43b541953":{
      "scriptId":"u38"},
    "01444ac81bfb434b9dddf8c1200b1aaf":{
      "scriptId":"u39"},
    "d16c5977e66741f1b7ce3571a61cefb5":{
      "scriptId":"u40"},
    "49f13855288743ef8a3a5b6a619c0528":{
      "scriptId":"u41"},
    "feda06ea4b44419d952e410b78f2a35a":{
      "scriptId":"u42"},
    "cf178665c6384e62b01ecbdc74717689":{
      "scriptId":"u43"},
    "6d91de061ae2480f978cd8a097de88e7":{
      "scriptId":"u44"},
    "414988f92ea24303a89d921154df8a2b":{
      "scriptId":"u45"},
    "54cbb48a131c45718c6c8741234b5e3a":{
      "scriptId":"u46"},
    "fd5e790fc837482587c7120e88488be2":{
      "scriptId":"u47"},
    "5de6154cf59246e28bb632a32b94a066":{
      "scriptId":"u48"},
    "7dc361acaa1845babbe55850042291bf":{
      "scriptId":"u49"},
    "d2fd8b5f40164e85a6e69e25eb5bdb06":{
      "scriptId":"u50"},
    "07dc4dc33bad4980b2331c8d360c86cb":{
      "scriptId":"u51"},
    "682ebee2de9e4c04b1ec01db94fb78d8":{
      "scriptId":"u52"},
    "dca9e21cf16042cc89e2ee10ab7fd66e":{
      "scriptId":"u53"},
    "754be820a12e4058af6036a5c34d4667":{
      "scriptId":"u54"},
    "468e590a5cb048c29f3d4f6034e934e9":{
      "scriptId":"u55"},
    "1fb28c6e68c6404589b1ef291510846f":{
      "scriptId":"u56"},
    "ececf9a51ff44cb8a2101647a3a63be2":{
      "scriptId":"u57"},
    "2f87bf6286c14aa4b5063a35e207ad5c":{
      "scriptId":"u58"},
    "77c1c8c8ef1647feb38cc3709628913c":{
      "scriptId":"u59"},
    "1968f181734e45149e3d508b44b90128":{
      "scriptId":"u60"},
    "ace2591e44dc495f8625403d3857e0aa":{
      "scriptId":"u61"},
    "70a5dc45b76e46cabe1850363bb23071":{
      "scriptId":"u62"},
    "20cc7ebafd2241b08b3f28934cb8a7b3":{
      "scriptId":"u63"},
    "64c1d908f95845fc9461b36596d2cd12":{
      "scriptId":"u64"},
    "0042b545efa449f5b0b9b553d9c93467":{
      "scriptId":"u65"},
    "038c6f8d71e9452aa3825be1f5bc961f":{
      "scriptId":"u66"},
    "e97cc1f4e5d14c5bac24a0c083ac7d42":{
      "scriptId":"u67"},
    "770594510d044d58a6abc63f8c32e42f":{
      "scriptId":"u68"},
    "d38e80368d6c4eb6afcde1722c3a0ef3":{
      "scriptId":"u69"},
    "9006cd27347642afbdd173a5f90ba967":{
      "scriptId":"u70"},
    "bf4a876a27dd4fb69a13ce1b1bd32b94":{
      "scriptId":"u71"},
    "862cbc57768b4f39bda6e8258143308e":{
      "scriptId":"u72"},
    "fffc0bced9f54b619d0d8ed2dc6a6c2f":{
      "scriptId":"u73"},
    "8af4042ea202431683168338a98e7b09":{
      "scriptId":"u74"},
    "f7e5c5cb6d664e8a81388ed761e99a69":{
      "scriptId":"u75"},
    "8a714fa1c4ac4d2bb840dfd830fd9362":{
      "scriptId":"u76"},
    "06840034ed384d74b9f52cf9189de97a":{
      "scriptId":"u77"},
    "5f3e2fdb6c2b456d9a593e30cf312163":{
      "scriptId":"u78"},
    "864a3bdfd8244b0ab812ed81c2206690":{
      "scriptId":"u79"},
    "ad5529c09540421f9420c1a6266ce5a5":{
      "scriptId":"u80"},
    "a7714999b1a44a949cb3c93b37e8e74e":{
      "scriptId":"u81"},
    "58df245d720a49638865fc9b874a4bcf":{
      "scriptId":"u82"},
    "9fb69b7e2a624a52862e96951ae6b54d":{
      "scriptId":"u83"},
    "d2fdb26380b240e1a8b2f52bc033cc19":{
      "scriptId":"u84"},
    "01d97f4ab3eb451797974d36ef103a18":{
      "scriptId":"u85"},
    "f03548610f734ef3b488a09e92a0197b":{
      "scriptId":"u86"},
    "05a69e6008a54b89aba86d1a0bedc0f0":{
      "scriptId":"u87"},
    "71664971beda42bbb85e52f008b89e66":{
      "scriptId":"u88"},
    "5aeaff1a2f7744c29ca60bd3339f43d9":{
      "scriptId":"u89"},
    "443fbcd152694ed5bdcba7c39b9fd241":{
      "scriptId":"u90"},
    "fca1c1a11cd5454ab919d5e811c3312b":{
      "scriptId":"u91"},
    "617b66764f194099b16f4bc8a6f17063":{
      "scriptId":"u92"},
    "4104d27500054eb0bb51e0beda042fc5":{
      "scriptId":"u93"},
    "82bccdde15d94156b2ae0b19ef2d0dd0":{
      "scriptId":"u94"},
    "25829e76fc1f47a7a3f5d9fdeb7b4d37":{
      "scriptId":"u95"}}});